name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VIRTUOSO_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
    steps:
      - name: Set up JDK 15
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "corretto"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clone local Repository
        uses: actions/checkout@v6

      - name: Build the Docker images and Push to Dockerhub
        run: bash -c ./service_config/build_images.sh

      - name: Init update
        uses: WSE-research/docker-service-updater@v0.2.1
        with:
          api_key: ${{ secrets.API_KEY }}
          updater_host: ${{ secrets.UPDATER_HOST }}
